server.port=${PORT:8080}
spring.application.name=backend

# Database PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-autumn-butterfly-zamh6gmy-pooler.c-2.eu-west-2.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_U7yBZDIkAK6M}

# HikariCP Pool
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=900000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.keepalive-time=30000

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true